[pytest]
addopts = -v --tb=short --strict-markers --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: быстрые проверки
    regression: полный регресс
    password: тесты настроек пароля

log_cli = true
log_cli_level = INFO